config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :student_classes
  resources :teachers
  resources :students
  get 'home/index'
  root "home#index"

  devise_for :users, controllers: {
  invitations: 'invitations', # Use your actual controller name here
  registrations: 'users/registrations' # If needed
}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 Welcome to the Digital Taylor Frame!
%p Forget your regular bag and heavy traditional tailor! Embrace the future of learning.
%p Our digital frame empowers blind students to excel in mathematics.
.features
  .feature
    %h2 Accessible Learning
    %p Our digital Taylor frame provides an accessible learning experience for blind students, enabling them to engage with mathematics like never before.
  .feature
    %h2 Portable and Convenient
    %p Say goodbye to bulky textbooks and equipment. Our digital frame is lightweight and portable, making it easy to carry and use anywhere, anytime.

- if user_signed_in?
  %h2 Welcome Home, #{current_user.email}  
  %br/
  %li
    %ul= link_to "Students", students_path
    %ul= link_to "Teachers", teachers_path
    %ul= link_to "Class information", student_classes_path

    %ul= button_to "Log out", destroy_user_session_path, method: :delete
- elsif admin_signed_in?
  %h2 Welcome Home, #{current_admin.email}  (Admin)
  %br/
  %li
    %ul= link_to "Students", students_path
    %ul= link_to "Teachers", teachers_path
    %ul= link_to "Class information", student_classes_path
    %ul= link_to "Invite Teacher", new_user_invitation_path
    %ul= button_to "Log out", destroy_admin_session_path, method: :delete
- else
  %h2 Log in / Sign up here:
  = link_to 'Sign in', new_user_session_path

  = link_to 'Sign in admin', new_admin_session_path