config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :student_classes
  resources :teachers
  resources :students
  get 'home/index'
  root "home#index"

  devise_for :users, controllers: {
  invitations: 'invitations', # Use your actual controller name here
  registrations: 'users/registrations' # If needed
}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/teacher.rb
class Teacher
  include Mongoid::Document
  include Mongoid::Timestamps
  field :firstname, type: String
  field :lastname, type: String
  field :mobile, type: String
  field :dateofbirth, type: Date
  field :gender, type: String
  validates :firstname, :lastname, :mobile, :dateofbirth, :gender, :presence => true
  belongs_to :user
  has_and_belongs_to_many :student_classes

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy!

    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:firstname, :lastname, :mobile, :dateofbirth, :gender, :user_id)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@teacher) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :firstname
    = f.input :lastname
    = f.input :mobile, as: :integer
    = f.input :gender, as: :radio_buttons, collection: [['Male', 'male'], ['Female', 'female'], ['Other', 'other']]
    = f.input :dateofbirth
    =f.hidden_field :user_id, :value => current_user.id

  .form-actions
    = f.button :submit

app/views/teachers/edit.html.haml
%h1 Editing teacher

= render 'form'

= link_to 'Show', @teacher
\|
= link_to 'Back', teachers_path

app/views/teachers/index.html.haml
%h1 Listing teachers

%table
  %thead
    %tr
      %th Firstname
      %th Lastname
      %th Mobile
      %th Dateofbirth
      %th Gender
      %th
      %th
      %th

  %tbody
    - @teachers.each do |teacher|
      %tr
        %td= teacher.firstname
        %td= teacher.lastname
        %td= teacher.mobile
        %td= teacher.dateofbirth
        %td= teacher.gender
        %td= link_to 'Show', teacher
        %td= link_to 'Edit', edit_teacher_path(teacher)
        %td= button_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Teacher', new_teacher_path

app/views/teachers/new.html.haml
%h1 New teacher

= render 'form'

= link_to 'Back', teachers_path

app/views/teachers/show.html.haml
%p#notice= notice

%p
  %b Firstname:
  = @teacher.firstname
%p
  %b Lastname:
  = @teacher.lastname
%p
  %b Mobile:
  = @teacher.mobile
%p
  %b Dateofbirth:
  = @teacher.dateofbirth
%p
  %b Gender:
  = @teacher.gender

= link_to 'Edit', edit_teacher_path(@teacher)
\|
= link_to 'Back', teachers_path