config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :student_classes
  resources :teachers
  resources :students
  get 'home/index'
  root "home#index"

  devise_for :users, controllers: {
  invitations: 'invitations', # Use your actual controller name here
  registrations: 'users/registrations' # If needed
}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/student_classes_controller.rb
class StudentClassesController < ApplicationController
  before_action :set_student_class, only: %i[ show edit update destroy ]

  # GET /student_classes or /student_classes.json
  def index
    @student_classes = StudentClass.all
  end

  # GET /student_classes/1 or /student_classes/1.json
  def show
  end

  # GET /student_classes/new
  def new
    @student_class = StudentClass.new
  end

  # GET /student_classes/1/edit
  def edit
  end

  # POST /student_classes or /student_classes.json
  def create
    @student_class = StudentClass.new(student_class_params)

    respond_to do |format|
      if @student_class.save
        format.html { redirect_to student_class_url(@student_class), notice: "Student class was successfully created." }
        format.json { render :show, status: :created, location: @student_class }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_classes/1 or /student_classes/1.json
  def update
    respond_to do |format|
      if @student_class.update(student_class_params)
        format.html { redirect_to student_class_url(@student_class), notice: "Student class was successfully updated." }
        format.json { render :show, status: :ok, location: @student_class }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_classes/1 or /student_classes/1.json
  def destroy
    @student_class.destroy!

    respond_to do |format|
      format.html { redirect_to student_classes_url, notice: "Student class was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_class
      @student_class = StudentClass.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_class_params
      params.require(:student_class).permit(:classname, :school)
    end
end

app/helpers/student_classes_helper.rb
module StudentClassesHelper
end

app/views/student_classes/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@student_class) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :classname
    = f.input :school

  .form-actions
    = f.button :submit

app/views/student_classes/edit.html.haml
%h1 Editing student_class

= render 'form'

= link_to 'Show', @student_class
\|
= link_to 'Back', student_classes_path

app/views/student_classes/index.html.haml
%h1 Listing student_classes

%table
  %thead
    %tr
      %th Classname
      %th School
      %th
      %th
      %th

  %tbody
    - @student_classes.each do |student_class|
      %tr
        %td= student_class.classname
        %td= student_class.school
        %td= link_to 'Show', student_class
        %td= link_to 'Edit', edit_student_class_path(student_class)
        %td= link_to 'Destroy', student_class, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Student class', new_student_class_path

app/views/student_classes/new.html.haml
%h1 New student_class

= render 'form'

= link_to 'Back', student_classes_path

app/views/student_classes/show.html.haml
%p#notice= notice

%p
  %b Classname:
  = @student_class.classname
%p
  %b School:
  = @student_class.school

= link_to 'Edit', edit_student_class_path(@student_class)
\|
= link_to 'Back', student_classes_path